name: Run GitScraper and Fetch Chart

on:
 workflow_dispatch:
 
jobs:
  run-gitscraper:
    runs-on: ubuntu-latest
    permissions: 
     contents: write
     actions: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      
      
      - name: Pull and run GitScraper container
        run: |
          docker pull rasmusrlarsen/gitscraper:latest
          docker run -d -p 8080:8080 rasmusrlarsen/gitscraper:latest
          sleep 10

      - name: Fetch chart
        run: |
          RESPONSE_HEADERS=$(mktemp)
          curl -L -s -o timechart.png -D $RESPONSE_HEADERS \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "http://localhost:8080/generate-chart?org=ITU-DevOps2025-GROUP-A&repo=itu-minitwit"

          CONTENT_TYPE=$(grep -i "Content-Type:" $RESPONSE_HEADERS | awk '{print $2}' | tr -d '\r')

          if [[ "$CONTENT_TYPE" != "image/png" ]]; then
            echo "Error: The response is not an image. Possible API failure."
            cat timechart.png  # Show what was saved for debugging
            exit 1
          fi
          
      - name: Get current date for versioning
        run: echo "RELEASE_TAG=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release & Upload Image
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Timechart Release - ${{ env.RELEASE_TAG }}"
          body: "Generating timechart..."
          files: timechart.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Image URL & Update Release
        run: |
          RELEASE_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/RasmusLarsen02/${{ github.repository }}/releases/tags/${{ env.RELEASE_TAG }}")
      
          IMAGE_URL=$(echo "$RELEASE_DATA" | jq -r '.assets[] | select(.name=="timechart.png") | .browser_download_url')
      
          if [[ -z "$IMAGE_URL" || "$IMAGE_URL" == "null" ]]; then
            echo "Error: Could not retrieve image URL"
            exit 1
          fi
      
          UPDATED_BODY="### Timechart Report\n\n![Timechart]($IMAGE_URL)"
      
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"$UPDATED_BODY\"}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.RELEASE_TAG }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
