name: Run GitScraper and Fetch Chart

on:
 workflow_dispatch:
 
jobs:
  run-gitscraper:
    runs-on: ubuntu-latest
    permissions: 
     contents: write
     actions: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Pull and run GitScraper container
        run: |
          docker pull rasmusrlarsen/gitscraper:latest
          docker run -d --name gitscraper --network=host rasmusrlarsen/gitscraper:latest
          sleep 10

      - name: Fetch chart
        run: |
          curl -L \
            -H "Authorization: token ${{ secrets.FINE_TOKEN }}" \
            "http://localhost:8080/generate-chart?org=ITU-DevOps2025-GROUP-A&repo=itu-minitwit" \
            -o timechart.png
            --write-out "%{http_code}\n" --silent --output /dev/null
          file timechart.png
          ls -lh timechart.png

      - name: Get current date for versioning
        run: echo "RELEASE_TAG=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Timechart Release - ${{ env.RELEASE_TAG }}"
          body: "Automated release with the latest generated timechart."
          files: timechart.png
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_TOKEN }}
